import { Category, SubCategory } from '../types/category';

export const yogaPoses: {
  id: number;
  name: string;
  translation: string;
  indianName: string;
  image: string;
  thumbnail: string;
  category: Category;
  subCategory?: SubCategory;
  linked?: number[];
}[] = [
  {
    id: 1,
    name: "Plough Pose",
    translation: "Halasana",
    indianName: "Halasana",
    image: "/yoga-skribbles/1_ploughpose.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.LAYING,
    subCategory: SubCategory.UPWARD,
    linked: [18],
  },
  {
    id: 2,
    name: "Child's Pose",
    translation: "Balasana",
    indianName: "Balasana",
    image: "/yoga-skribbles/2_childspose.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.LAYING,
    subCategory: SubCategory.UPWARD,
    linked: [1],
  },
  {
    id: 3,
    name: "Bow Pose",
    translation: "Dhanurasana",
    indianName: "Dhanurasana",
    image: "/yoga-skribbles/3_bowpose.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.LAYING,
    subCategory: SubCategory.DOWNWARD,
    linked: [7],
  },
  {
    id: 4,
    name: "Lotus Pose",
    translation: "Padmasana",
    indianName: "Padmasana",
    image: "/yoga-skribbles/4_lotuspose.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.SITTING,
    linked: [5],
  },
  {
    id: 5,
    name: "Staff Pose",
    translation: "Dandasana",
    indianName: "Dandasana",
    image: "/yoga-skribbles/5_staffpose.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.SITTING,
    linked: [6],
  },
  {
    id: 6,
    name: "Hero Pose",
    translation: "Virasana",
    indianName: "Virasana",
    image: "/yoga-skribbles/6_heropose.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.SITTING,
    linked: [2],
  },
  {
    id: 7,
    name: "Plank Pose",
    translation: "Phalakasana",
    indianName: "Phalakasana",
    image: "/yoga-skribbles/7_plankpose.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.HALF_STANDING,
    subCategory: SubCategory.UPWARD,
    linked: [15, 16],
  },
  {
    id: 8,
    name: "Tabletop Pose",
    translation: "Bharmanasana",
    indianName: "Bharmanasana",
    image: "/yoga-skribbles/8_tabletoppose.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.HALF_STANDING,
    subCategory: SubCategory.UPWARD,
    linked: [16],
  },
  {
    id: 9,
    name: "Wheel Pose",
    translation: "Chakrasana",
    indianName: "Chakrasana",
    image: "/yoga-skribbles/9_wheelpose.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.HALF_STANDING,
    subCategory: SubCategory.DOWNWARD,
    linked: [10],
  },
  {
    id: 10,
    name: "Bridge Pose",
    translation: "Setu Bandha Sarvangasana",
    indianName: "Setu Bandha Sarvangasana",
    image: "/yoga-skribbles/10_bridgepose.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.HALF_STANDING,
    subCategory: SubCategory.DOWNWARD,
    linked: [9, 18],
  },
  {
    id: 11,
    name: "Triangle Pose",
    translation: "Trikonasana",
    indianName: "Trikonasana",
    image: "/yoga-skribbles/11_trianglepose.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.STANDING,
    subCategory: SubCategory.GROUNDING,
    linked: [12, 13],
  },
  {
    id: 12,
    name: "Warrior I",
    translation: "Virabhadrasana I",
    indianName: "Virabhadrasana I",
    image: "/yoga-skribbles/12_warrieri.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.STANDING,
    subCategory: SubCategory.GROUNDING,
    linked: [13],
  },
  {
    id: 13,
    name: "Warrior III",
    translation: "Virabhadrasana III",
    indianName: "Virabhadrasana III",
    image: "/yoga-skribbles/13_warrioriii.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.STANDING,
    subCategory: SubCategory.BALANCING,
    linked: [14],
  },
  {
    id: 14,
    name: "Half Moon",
    translation: "Ardha Chandrasana",
    indianName: "Ardha Chandrasana",
    image: "/yoga-skribbles/14_halfmoon.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.STANDING,
    subCategory: SubCategory.BALANCING,
    linked: [13],
  },
  {
    id: 15,
    name: "Down Dog",
    translation: "Adho Mukha Svanasana",
    indianName: "Adho Mukha Svanasana",
    image: "/yoga-skribbles/15_downdog.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.INVERSION,
    subCategory: SubCategory.PARTIAL,
    linked: [7],
  },
  {
    id: 16,
    name: "Fold Forward",
    translation: "Uttanasana",
    indianName: "Uttanasana",
    image: "/yoga-skribbles/16_foldforward.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.INVERSION,
    subCategory: SubCategory.PARTIAL,
    linked: [15],
  },
  {
    id: 17,
    name: "Headstand",
    translation: "Shirshasana",
    indianName: "Shirshasana",
    image: "/yoga-skribbles/17_headstand.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.INVERSION,
    subCategory: SubCategory.TOTAL,
    linked: [2],
  },
  {
    id: 18,
    name: "Shoulder Stand",
    translation: "Sarvangasana",
    indianName: "Sarvangasana",
    image: "/yoga-skribbles/18_shoulderstand.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.INVERSION,
    subCategory: SubCategory.TOTAL,
    linked: [1],
  },
  // New poses 1-4 (Standing category)
  {
    id: 19,
    name: "Pose 1",
    translation: "Pose 1",
    indianName: "Pose 1",
    image: "/yoga-skribbles/pose1.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.STANDING,
    subCategory: SubCategory.GROUNDING,
    linked: [],
  },
  {
    id: 20,
    name: "Pose 2", 
    translation: "Pose 2",
    indianName: "Pose 2",
    image: "/yoga-skribbles/pose2.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.STANDING,
    subCategory: SubCategory.BALANCING,
    linked: [],
  },
  {
    id: 21,
    name: "Pose 3",
    translation: "Pose 3",
    indianName: "Pose 3",
    image: "/yoga-skribbles/pose3.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.STANDING,
    subCategory: SubCategory.GROUNDING,
    linked: [],
  },
  {
    id: 22,
    name: "Pose 4",
    translation: "Pose 4",
    indianName: "Pose 4",
    image: "/yoga-skribbles/pose4.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.STANDING,
    subCategory: SubCategory.BALANCING,
    linked: [],
  },
  // New poses 5-8 (Half Standing category)
  {
    id: 23,
    name: "Pose 5",
    translation: "Pose 5",
    indianName: "Pose 5",
    image: "/yoga-skribbles/pose5.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.HALF_STANDING,
    subCategory: SubCategory.UPWARD,
    linked: [],
  },
  {
    id: 24,
    name: "Pose 6",
    translation: "Pose 6",
    indianName: "Pose 6",
    image: "/yoga-skribbles/pose6.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.HALF_STANDING,
    subCategory: SubCategory.DOWNWARD,
    linked: [],
  },
  {
    id: 25,
    name: "Pose 7",
    translation: "Pose 7",
    indianName: "Pose 7",
    image: "/yoga-skribbles/pose7.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.HALF_STANDING,
    subCategory: SubCategory.UPWARD,
    linked: [],
  },
  {
    id: 26,
    name: "Pose 8",
    translation: "Pose 8",
    indianName: "Pose 8",
    image: "/yoga-skribbles/pose8.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.HALF_STANDING,
    subCategory: SubCategory.DOWNWARD,
    linked: [],
  },
  // Flatten pose for testing
  {
    id: 27,
    name: "Flatten Pose",
    translation: "Flatten Pose",
    indianName: "Flatten Pose",
    image: "/yoga-skribbles/flatten pose.svg",
    thumbnail: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwIDIwTDEwIDMwTDIwIDQwTDMwIDMwTDIwIDIwWiIgZmlsbD0iY3VycmVudENvbG9yIi8+Cjwvc3ZnPgo=",
    category: Category.STANDING,
    subCategory: SubCategory.GROUNDING,
    linked: [],
  },
];

export const yogaCategories = [
  {
    category: Category.LAYING,
    title: "Laying",
    subCategories: [
      {
        subCategory: SubCategory.UPWARD,
        title: "Upward",
      },
      {
        subCategory: SubCategory.DOWNWARD,
        title: "Downward",
      },
    ],
  },
  {
    category: Category.SITTING,
    subCategories: [],
    title: "Sitting",
  },
  {
    category: Category.HALF_STANDING,
    title: "Half Standing",
    subCategories: [
      {
        subCategory: SubCategory.UPWARD,
        title: "Upward",
      },
      {
        subCategory: SubCategory.DOWNWARD,
        title: "Downward",
      },
    ],
  },
  {
    category: Category.STANDING,
    title: "Standing",
    subCategories: [
      {
        subCategory: SubCategory.GROUNDING,
        title: "Grounding",
      },
      {
        subCategory: SubCategory.BALANCING,
        title: "Balancing",
      },
    ],
  },
  {
    category: Category.INVERSION,
    title: "Inversion",
    subCategories: [
      {
        subCategory: SubCategory.PARTIAL,
        title: "Partial",
      },
      {
        subCategory: SubCategory.TOTAL,
        title: "Total",
      },
    ],
  },
];